### ISSUE TITLE
Killed: 9

### ISSUE THREAD

**Issue by storer1017** [4ureliek/Parsing-RepeatMasker-Outputs#1]
I am very glad to have found these files! I hope to utilize them for my RepeatMasker output. However, after running a small test on a sample out file, I received the following error:
Killed: 9.
I couldn't find this message in the code provided. Any suggestions?

**Comment by 4ureliek** [comment]
Hi,
Killed:9 is a kill signal form the server.
Could you email me your command line? Did you use the -v option, and if yes can you send me everything that the script printed?
Thanks!

**Comment by 4ureliek** [comment]
Solved in parseRM.pl v5.0 update
