### ISSUE TITLE
getting error while parsing RMoutput

### ISSUE THREAD

**Issue by Ravindra-Raut** [4ureliek/Parsing-RepeatMasker-Outputs#10]
Getting error after installing Bio::SeqIO module. 

To run scripts, the environment is created using python3, conda, biopython, R, Bioperl modules: Bio::SeqIO, Statistics:R, fork. But still facing error mentioning following dialogue: Please suggest a solution.

Configuring BioPerl-1.7.8 ... OK
Building and testing BioPerl-1.7.8 ... OK
Successfully reinstalled BioPerl-1.7.8
2 distributions installed
(base) ravindraraut@Ravindras-MacBook-Air Leersia_perrieri % perl parseRM.pl -i Leersia_perrieri.fa.out  -p
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.2/darwin-thread-multi-2level /Library/Perl/Updates/5.30.2 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at parseRM.pl line 11.
BEGIN failed--compilation aborted at parseRM.pl line 11.

**Comment by 4ureliek** [comment]
Hi,
Unfortunately I never used anaconda for perl, so at this point forums online may have more advice than what I can give you...! My only suggestion would be to edit the code to add the path to where Bio::SeqIO is installed into @inc.
