### ISSUE TITLE
how to choose the substitution rate

### ISSUE THREAD

**Issue by ChenXi1201** [4ureliek/Parsing-RepeatMasker-Outputs#11]
Hi！this tools is great. 
I wonder how to choose the substitution rate. The example is 0.0021, but how to know the substitution rate of my own species? 
This article quotes your tool to estimate the timing of TE insertions, but does not describe the substitution rate. 
https://www.nature.com/articles/s41467-022-28585-1
I wonder if the default 0.0021 is OK？
And I have species trees, can I get the substitution rate of my own species from the species tree?

**Comment by 4ureliek** [comment]
Hi,
Unfortunately, to be accurate you'd need an estimation for your species. You can use any value if you do not have one, but that means your branch lengths will also be not reliable (but, they will be proportioned, so you can still compare short/long). 
I relied on literature so I do not have specific any advice on how to calculate it yourself - besides looking for methods in the literature! 
Good luck

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦
