### ISSUE TITLE
% of repeatable elements inconsistent between -age and -landscape

### ISSUE THREAD

**Issue by evo-eco-gen** [4ureliek/Parsing-RepeatMasker-Outputs#12]
Hello,

Thanks for a great set of tools!
I have run parseRM.pl in both the 'age' and 'landscape' mode, based on the .align output of RepeatMasker. The landscape plots suggest a lot of recent accumulation. LTRs alone contributed ~1.5% of the genome in the last 2.5Myr, and ~10% of the genome in the last 5M years.
However, the -a estimates tell a very different story: the total of the genome derived from repeats (all repeats, not just LTRs!) is 0.61% in the last 2.5Myr, and 6.7% in the last 5Myr. 
Why such a difference, especially for the 2.5Myr interval? I attach the results from both.
[landscape_1row.pdf](https://github.com/4ureliek/Parsing-RepeatMasker-Outputs/files/11963196/landscape_1row.pdf)
[ParseRM.repeatAges.txt](https://github.com/4ureliek/Parsing-RepeatMasker-Outputs/files/11963199/ParseRM.repeatAges.txt)

**Comment by 4ureliek** [comment]
Hi,
Could you share, at a minimum: your full command lines; and at best: smaller inputs reproducing the issue, with command lines and outputs? I have not worked with this in a long time, and have left the world of TE work, so I don't have any files to work with and look at things. 

The code does not really do anything fancy, it just loads bp from the .align files and split things into bins, and the data for both outputs is in fact loaded only once... It's just printed differently.

Two things come to mind, and I think the first one could be it:
- what about a plot for all? I checked the code briefly, and looks like the %div is stored for each position that is masked; so if there are overlaps between some TE families and non TE sequences, it seems like it would lead to some discrepancies: when everything is looked at nonTE sequences are skipped but by family, the family takes precedence over nonTE sequences - so I'd bet the nonTE pieces are that 'recent' peak... Made sense at the time (if a TE contains nonTE pieces like low complexity, they'd still be part of the TE itself when calculating an amount; but the issue could be that the mutations saturate faster in low complexity, and they appear younger..?
- what about removing all My considerations and check how things look like with just % divergence? Always helps debugging to remove layers of complexity
