### ISSUE TITLE
no output generated

### ISSUE THREAD

**Issue by Nicholas-Kron** [4ureliek/Parsing-RepeatMasker-Outputs#13]
Hi there,

I am currently assembling and annotating a fish genome. I have been following along on Dr. Daren Card's [repeat classification](https://darencard.net/blog/2022-07-09-genome-repeat-annotation/) workflow. In it he recommends your scripts over the utility packaged with RepeatMasker to generate for repeat landscapes because of the more tractable output. I downloaded the scripts into the /bin of the conda env I use for RepeatMasker, and edited the scripts #! and @inc statements to route to the proper perl install and libraries. I am running the script on a CentOS7 LSF HPC cluster. I can get the program to run, but I do not get any of the final output files. The LSF outfile states the job ran to completion without error, and indeed the LSF error file is also empty. I get some log information, but nothing after looping through the array. Any idea what could be happening?

the command:
```
parseRM.pl -v -i 05_full_out/${GENOME}.full_mask.align -p -g ${allLen} -l 50,1 2>&1 | tee logs/06_parserm.log
```

the log output:
```
--------------------------------------------------
 --- Script parseRM.pl started (v5.8.2), with:
      - Input file = 05_full_out/fOpsBet2.1_genomic.full_mask.align
      - All non TE repeats will be filtered out
      => global parsing will be done, with following options:
         - length(s) are given instead (--glen 2151823914)
      => landscape data will be generated, with following options:
         - With max_bin,bin_len = 50,1
--------------------------------------------------
 --- Prepping steps for --parse...
     - Loading sequence length(s) from 2151823914...
 --- Now parsing RM output(s)
     -> 05_full_out/fOpsBet2.1_genomic.full_mask.align..
        ..loading in array..
          ..done
        ..Looping through array (parsing)..
```

**Comment by 4ureliek** [comment]
I never ran this on a cluster; I wonder if the memory allocation is creating issues? When you submit jobs, do you request memory or is that allocated on the fly? Have you tried running the code on a test file (e.g. get the first few repeats from your input and use that as input)?

**Comment by Nicholas-Kron** [comment]
That may have been the issue. The job script only requested 5 cores at 1Gb each. I ran the script with a subset of 10k lines from the .align and it worked fine. Resubmitted with 10 cores @ 5Gb each. Will report back on how that goes, but I have a feeling this will solve it. Thanks for your help!
