### ISSUE TITLE
About the low speed in parseRM.pl

### ISSUE THREAD

**Issue by BioWu** [4ureliek/Parsing-RepeatMasker-Outputs#2]
Thanks for your works for providing such scripts. They are very useful. I applied the ```parseRM.pl``` script in my works. The genomes I worked now, are heavily fragmented. So, I got very slow speed running this tool. After the ```NYTProf``` (one perl module) was used to identify which steps had token such long time.  I found the ```get_data()``` function and the ```undef $id; ``` sentence toke long time. In the ```get_data()``` function, the ```@div = sort @div if ($div[0]); ``` toke large time. For my jobs, several days had been spent on running this. So, I try to ask  you for help. Hopping you could refine this tool. 

Thanks!
:)

**Comment by 4ureliek** [comment]
Hi,
Indeed, sorry about that! I am aware of the issue but haven't gotten around fixing it... As a 'bandage' fix, you may use the parseRM_simple.pl script to parse *.out files, it will be much faster.
I really appreciate your input on which part is taking the most time!
Best,
~A

**Comment by 4ureliek** [comment]
I removed that step so it should speed things a little, but I will try to speed it more.

**Comment by BioWu** [comment]
I had tried yesterday, speed of this tool increased significantly. 
Thanks for your efforts!

**Comment by 4ureliek** [comment]
Thanks!
The reason it is still slow is that I load a %div for each masked position of a contig/scaffold/chromosome. It would be better and much faster to deal with segments of DNA of same %div, but I have not gotten around doing this. Someday!

**Comment by BioWu** [comment]
Hello Aurelie,
  In both the parseRM_GetLandScapeXX.pl and parseRM.pl, the overlapping
annotation in RepeatMasker output file were all used ? It this right ?
Should I manually select one best for each overlapping blocks?

Thanks!

**Comment by 4ureliek** [comment]
Hi,
When parsing a .align, if there is any overlap, the repeat masking with the smallest %div at a given position is kept. This assumes that if there is a recent repeat identified, it means that even if older repeat mask this position, then the recent one is what we should use. Note that this is different than what RM does from .align to .out files: it will keep the whole length and merge, and averaging the %div.

**Comment by BioWu** [comment]
Hi,
  In my results, I found the total genome proportion masked summarized by
parseRM.pl was two fold greater than result generated by
parseRM_GetLandScape.pl.  And the later is closed to the RepeatMasker *.tbl
files result. I have checked two different samples, both of them showed
above results. Besides, I calculated the TE proportion manually using the
masked length (*.summary.tab). The results were two-fold smaller than
proportions provided in the summary table file. Could you help me to solve
this?

Thanks!

**Comment by 4ureliek** [comment]
Hi,
That's weird, I had checked manually with a test file that the numbers were OK. I will look into it, but make sure that you look at the column that says nt_masked-minus-double

**Comment by 4ureliek** [comment]
Hi,
I pushed an update that fixes bugs in the DNA amounts - the 'nt_masked-minus-double' was OK, but the rest were wrong. I also fixed another bug regarding the loading of the kimura corrected %div from .align.
Thanks!

**Comment by 4ureliek** [comment]
Hi,
I just pushed a new version that is still slower than I'd like, but ran in a few hours on a bird genome.
