### ISSUE TITLE
parseRM.pl --land Memory usage

### ISSUE THREAD

**Issue by kkuonjj** [4ureliek/Parsing-RepeatMasker-Outputs#3]
Hey, 

thanks for sharing your scripts with the community. I just run a couple of them (i.e. parseRM_simple.pl). However, I'm struggling to run parseRM --land for drawing good looking plots. 
I'm running the script on a Repeatmasker out file (with 144Mb in size) and would like to split the genome into 10Mb bins. The fasta file has around 1.2Gb. 

I hope this is going to help other users as well. 
j

**Comment by 4ureliek** [comment]
Hi,
If I understood well what you are trying to do, you won't be able to do it with my script. The parseRM.pl --land option is for graphs such as [this one](https://iiif.elifesciences.org/lax:19090/elife-19090-fig6-v2.tif/full/full/0/default.jpg). The bins are the % of divergence of the DNA fragments masked as repeat X to the consensus of repeat X. It seems that you would like to plot TE content from genome bins such as [this figure](https://iiif.elifesciences.org/lax:19090/elife-19090-fig2-v2.tif/full/,1500/0/default.jpg) or the last figure of [this paper](http://onlinelibrary.wiley.com/doi/10.1111/nyas.13295/full). I do not have a script to do that, but for the second link we published the R code to build the plot: it needs files with the TE content by bin (we had one file per TE class), which can be done with R or Galaxy I think.
Hope this helps,
Cheers,
Aurelie
