### ISSUE TITLE
Different result with RepeatMasker

### ISSUE THREAD

**Issue by ptranvan** [4ureliek/Parsing-RepeatMasker-Outputs#7]
Hi,

Thanks for your program. I have a question about the result. 
This is my command and the result:

`perl Parsing-RepeatMasker-Outputs/parseRM.pl -i ../Genome.fasta.out -p
`
```
#nt_total_in_genome     nt_masked-minus-double  %_masked        FYI:nt_masked_double
nd      92239330        nd      5466827
```

As we can see, the total number masked is `92239330` bp ... which is different from Repeatmasker.tbl output:

`Total interspersed repeats:    91273809 bp   31.21 %`

Why this difference ?

**Comment by 4ureliek** [comment]
Hi,

Unsure, actually. I never benchmarked against these results, only with test/dummy files I had for .out and .align files.
Could you check if somehow some non TE stuff were kept in my output, even though they should have been filtered out?
The tbl output is for interspersed repeats only, so that could be the issue.

**Comment by ptranvan** [comment]
I have very close number between your output and Repeatmasker:

Your output:

```
#class  nt_masked-minus-double  %_masked        FYI:nt_masked_double
DNA     17808709        6.08979198087849        697761
LINE    6990023 2.3902791612551 294843
SINE    344571  0.117828064496044       8319
Unspecified     30      1.02586750912913e-05    0
RC      891706  0.304924071031832       32742
Retroposon      244     8.34372240758356e-05    41
LTR     12692539        4.34028778948476        450089
Unknown 53511508        18.2985724739011        3650173

```

RepeatMasker:

```
               number of      length   percentage
               elements*    occupied  of sequence
--------------------------------------------------
DNA transposons      30220     17833478 bp    6.10 %
   LINEs:             8135      7067944 bp    2.42 %
   SINEs:             1029       345499 bp    0.12 %
Rolling-circles       1224       889779 bp    0.30 %
   LTR elements:     12643     12708059 bp    4.35 %
Unclassified:       163171     53318829 bp   18.23 %
```

Different things that are not in Repeatmasker are `Unspecified` and `Retroposon`: they are very low. What is it ?

These different numbers among the 2 outputs, I am not sure to understand how is it computed too.

**Comment by 4ureliek** [comment]
My code takes the repeat names tename#class/family to output the class that you show. So it depends on your library. RM probably has some extra parsing. 

One thing to keep in mind is that when bases are masked by 2 TEs of the same class, I subtract that amount before reporting the amount for the class (but not if it is by TEs of a different class). 

I do not know what goes into the generation of this table output from RM - honestly the differences are not big, the % are so similar, that I wouldn't personally worry about it (it's not like any TE annotation is 'perfect'). Unfortunately I do not work on this anymore so I can't promise to dig into these differences. My guess is that they don't process overlaps in the same way than I do... I get my numbers from the .out here, while they probably get them from the .align files, with some processing.

If you want to dig, you can try to compare on a very small region that you could manually check, and see what's what. If you do that, please post here what you find!
