### ISSUE TITLE
Incorrect BED format?

### ISSUE THREAD

**Issue by brunocontrerasmoreira** [4ureliek/Parsing-RepeatMasker-Outputs#8]
Hi, I found the script 
https://github.com/4ureliek/Parsing-RepeatMasker-Outputs/blob/master/RMout_to_bed.pl
and tried it out with option <base0> and I believe the output is not correct.
As the BED format is 0-based (see https://m.ensembl.org/info/website/upload/bed.html for instance), the code should be substracting -1 to the start coord reported by RM, or am I missing something?
Hope this helps,
Bruno

**Comment by 4ureliek** [comment]
Ha, you are correct, thank you very much for posting an issue. When I wrote this I enabled converting the coordinates from base0 to base1, but not the other way around, which would be required for a proper bed format.
If you have some perl knowledge, please feel free to commit a fixed version of the code here!

Alternatively, awk, or python, could do this. Let me know and I can help writing the few required lines of code.

**Comment by brunocontrerasmoreira** [comment]
Please see https://github.com/4ureliek/Parsing-RepeatMasker-Outputs/pull/9

Note that the following Perl one-liner does the same job:

``` perl -lne 'if(/(\S+)\s+(\d+)\s+(\d+)\s+\(/){ printf("%s\t%d\t%d\n",$1,$2-1,$3) }'  RM.out ```

Bruno

**Comment by 4ureliek** [comment]
Thanks! 
Yes, this mini script was a "I'm learning perl" thing. 
Many alternatives: perl one liner, awk one liner... I really appreciate the help!
